### ISSUE TITLE
The paper

### ISSUE THREAD

**Issue by zhangzhangthink** [seorim0/NUNet-TLS#1]
Hello, as a newcomer who has just dabbled in speech enhancement, I really want to read your paper on this program. Excuse me for being stupid, I didn't find your paper on the Internet. Can you share it here?

**Comment by seorim0** [comment]
Hi!    

Since this paper was submitted to INTERSPEECH 2022 (acceptance has not yet been announced), it is not published elsewhere, and seems difficult to upload the full paper before the announcement.     
If there is something you do not understand or need an explanation for, I will help you.    
    
Thank you for your interest in our research.

**Comment by shenbuguanni** [comment]
When submitting INTERSPEECH, you can submit paper to arxiv at the same time?

**Comment by seorim0** [comment]
@shenbuguanni   
Unfortunately, I didn't submit it to the arXiv at the same time.
